name: CustomEntities
version: '1.0'
main: org.icecube.customentities.CustomEntities
api-version: '1.20'
commands:
  spawnfrog:
    permission:
      frog.use
permissions:
  frog.use:
    default: op

